### ISSUE TITLE
[코멘트 요청] 컴포넌트 구성에 관하여.

### ISSUE THREAD

**Issue by rriverr** [rriverr/hh99-React#1]
제 [프로젝트](https://github.com/rriverr/hh99-React/tree/main/my-dic)는 현재 
App(타이틀, 메인 컴포넌트) / Main(목록) / Addlist(추가폼)  의 구성으로 이루어져있는데, 
코드를 작성하다보니 스타일 컴포넌트까지 더해져 어디 있는지 모를 코드 몇 줄을 찾기 위해 매번 모든 파일을 한번씩 열어봐야 하는 불편함이 생겼습니다. 

😓 컴포넌트의 구성을 어떤 식으로 개선해야 작성하는 사람이나 보는 사람 모두에게 수정하기 편리하고 가독성 좋은 구성이 될까요? 

<br>

**Comment by nemyung** [comment]
안녕하세요 유나님! 금주 코멘트를 맡게된 오세명입니다. 좋은 고민거리를 가지고 질문을 해주셨습니다! 이 부분은 저도 여전히 고민하고 있고, 정해진 답이 존재하지 않는 부분이라서 저는 질문주신 부분에 대해 어떻게 생각하는지 주관적인 의견을 남겨보겠습니다. 취향이니까 이렇게 생각할 수도 있구나 고려해주시면 감사하겠습니다! 

1. Styled-Component에 관하여
  - 저는 항해를 수료한 이후로 지금까지 이 패키지를 사용하지 않았어요. tailwindCss라는 패키지를 좋아하기 때문이에요. 하지만 styled-component를 사용하는 프로젝트를 많이 봐왔습니다.
  - 단지 스타일 적용에 필요한 컴포넌트들은 하나의 (1)폴더 내지 (2)파일에 뭉치는 것을 많이 봤어요. 예를 들면 다음 처럼요.!
```jsx
//styles.js
export const Comp1 = styled.div``
export const Comp2 = styled.div``
export const Comp3 = styled.div``

...

import * as S from "styles.js"

return (
  <S.Comp1>
  </S.Comp1>
);
```
  - 스타일 적용이지만, 레이아웃에 관련된 컴포넌트들은 따로 layout이라는 폴더를 만들고 관리를 하는 것 처럼 보였습니다. 이런식으로 sytled-component 관련 파일을 뭉쳐두고 import 해서 관리해보시면 좋을 것 같다는 생각이 드네요.

2. 컴포넌트를 비즈니스 로직과 연계해서 바라보셨으면 좋겠습니다.
  - 일반적으로 하나의 페이지에는 작성하신 프로젝트처럼 하나의 비즈니스 로직을 보여줍니다. 하나의 비즈니스 로직은 곧 개발자가 가지는 하나의 관심사 영역이 되겠죠. 그 영역 별로 묶어서 관리를 해보시는 것을 추천해봅니다!
  - 지금은 사이즈가 작아 `src` 폴더에 많은 컴포넌트들이 있지만, 이걸 하나의 관심사로 합쳐보면 src/pages/dictionary 라는 폴더에 몇가지를 넣어 관리할 수도 있을 것 같습니다. 강의 내용을 다시 한 번 보시고 각 페이지가 어떤 관심사를 가지고 있는지 고민해보시면 유나님만의 유니크한 구조가 탄생할 것이라 생각합니다!


이상 코멘트 마치겠습니다. 좋은 주말 보내세요!

**Comment by rriverr** [comment]
안녕하세요! 친절한 코멘트 정말 감사합니다! 
심화주차 강의에서 다루어지는 컴포넌트 관리에 대한 설명이 조금 부족하다 느껴져 여전히 고민중이었는데, 세명님의 코멘트로 좀 더 구체적인 방향성이 잡히는 것 같습니다! 특히 비즈니스 로직과 연계해서 바라보라는 말씀이 크게 와닿는 것 같아요. 감사합니다!
